### ISSUE TITLE
Property P102_has_title without language indication

### ISSUE THREAD

**Issue by delahousse** [DOREMUS-ANR/knowledge-base#26]
We do not find the language indication on the property P102_has_title, is it possible to add it. This information is available in BnF notice.

**Comment by pasqLisena** [comment]
Hello @delahousse,
thanks for the issue. However the issues about the data conversion should be opened in the [marc2rdf repo](https://github.com/DOREMUS-ANR/marc2rdf/issues).

Finally, this bug is solved in [latest commit](https://github.com/DOREMUS-ANR/marc2rdf/commit/21f66a30b062e98d6ae1ab1d63af1838e5ebeb19).
