### ISSUE TITLE
Pivot graph of expressions

### ISSUE THREAD

**Issue by manoach** [DOREMUS-ANR/knowledge-base#37]
The equivalent expressions should have one URI in the pivot graph. 

The questions are:  

1. What is the pattern of these URIs?

The pattern can be : `http://data.doremus.org/expression/<uuid>` (see [#39](https://github.com/DOREMUS-ANR/marc2rdf/blob/master/URI.patterns.md))

2. Should we generate their UUID **randomly** or in a **deterministic** way?

I suggest not generating them **randomly** for not having duplications. We can combine the identifiers of the expressions referring to the same entity. For example: "0182286", "13920876" and "14975" from PP, BNF and RF respectively. But can we have the same identifier through the 3 institutions or they are unique?

**Comment by rtroncy** [comment]
Yes, we need to mint a **new** URI for the expressions in the pivot graph, the pivot being the sum of all graphs minus the duplicates. Yes, the URI should follow the ```http://data.doremus.org/expression/<uuid>``` pattern and indeed, the UUID cannot be completely random, since we don't want to have URI collision. The UUID is generally a hash function of some seed, so the question is what should be the seed. The seed could indeed be: "pivot"+[local_ID]+[local_ID]+... for as many matching found for this expression including a single one if this expression is not aligned to any other.

**Comment by manoach** [comment]
Finally, the UUID will be generated in the same way as for the expressions of each of the three institutions ([issue #16](https://github.com/DOREMUS-ANR/marc2rdf/issues/16)): dbName + recordId + classCode

**Comment by pasqLisena** [comment]
Do you mean this instead?
(dbName_1 + recordId_1) + (dbName_2 + recordId_2) + classCode

**Comment by manoach** [comment]
> Do you mean this instead?
(dbName_1 + recordId_1) + (dbName_2 + recordId_2) + classCode

Yes, this is it :)

**Comment by manoach** [comment]
For more details: we have 3 cases

**Case 1**: A resource has no equivalent (no link _**owl: sameAs**_ with another resource)

`dbName_1 + recordId_1 + classCode` ... Which will generate exactly the same URI of the resource in question.

**Case 2**: 2 equivalent resources from 2 institutions

`(dbName_1 + recordId_1) + (dbName_2 + recordId_2) + classCode`

**Case 3**: 3 equivalent resources from 3 institutions

`(dbName_1 + recordId_1) + (dbName_2 + recordId_2) + (dbName_3 + recordId_3) + classCode`

**Comment by kgtodorov** [comment]
In the case when a given expression exists in only one base, this scheme will lead to the creation of the same URI for that expression in the pivot graph. Don't we prefer that each expression has its 'pivot' uri, which is different from the one(s) found in the institution bases (and linked to these via owl:sameAs)?

**Comment by manoach** [comment]
> Case 1: A resource has no equivalent (no link owl: sameAs with another resource)
> dbName_1 + recordId_1 + classCode

As @kgtodorov has noticed, there is a small problem in **case 1**: 

The generated URI in the pivot graph will be exactly the same as that of the resource that has no equivalent. In this case, we will not be able to add an **_owl:sameAs_** link to the resource itself.

To ensure different UUIDs, the seed could be: `"pivot" + dbName_1 + recordId_1 + classCode` ... as it was mentioned by @rtroncy .

For the two other cases, the seed could be:

**Case 2**: `"pivot"+ (dbName_1 + recordId_1) + (dbName_2 + recordId_2) + classCode`

**Case 3**: `"pivot"+ (dbName_1 + recordId_1) + (dbName_2 + recordId_2) + (dbName_3 + recordId_3) + classCode`

**Comment by kgtodorov** [comment]
The question is if we want to have specific 'pivot' URIs for all expressions, or those that are unique can be used with their institutional URIs in the pivot.

**Comment by pasqLisena** [comment]
I think the final graph should contain at least one "line" (pivot entity) for each distinct work.
In other words:
-  if there is a match, it would contain `<PIVOT_URI> owl:sameAs <BASE1_URI>, <BASE2_URI>.`
- otherwise, it would contain anyway `<PIVOT_URI> owl:sameAs <BASE1_URI>`. It gives no information, but I think it will simplify a lot the queries.

About, URI, I think it doesn't really matter how URI are generate, as soon as the process is deterministic, replicable and documented.

**Comment by rtroncy** [comment]
As @pasqLisena said, don't try to burry semantics in a URI. This is just an identifier. It has to be unique and deterministic. This is why I proposed to use the term 'pivot' in the construction.

@manoach There are more than 3 cases, as you wrote in [this comment](https://github.com/DOREMUS-ANR/knowledge-base/issues/37#issuecomment-359428395) since we have up to 6 databases to interconnect (once DIABOLO will be in the game)

**Comment by manoach** [comment]
> @manoach There are more than 3 cases, as you wrote in this comment since we have up to 6 databases to interconnect (once DIABOLO will be in the game)

@rtroncy Yes, I agree with you ;)

**Comment by kgtodorov** [comment]
The question is not one of semantics, but simply of knowing whether we create a uri in the pivot for unique expressions. I think it has been cleared up now.
